### ISSUE TITLE
Validate all configs before updating

### ISSUE THREAD

**Issue by johankvint** [auth0/auth0-deploy-cli#100]
It would be nice if the import would validate all configs before anything is deployed.
In my case the STMP-port was a string instead of a number in my config file.
Everything was deploy up to the point where it should deploy the SMTP settings and I got an `Schema one of` error and it aborted.
Maybe that could have been checked before anything else was deployed?

**Comment by ed-sparkes** [comment]
Yes would be nice to have a way of validating the yaml which could be done in a build step in CI, then deploy to environment if all is good

**Comment by mmarinm** [comment]
I am having same issue

**Comment by willvedd** [comment]
Is the intent here to validate that the configuration is valid yaml or valid in an Auth0 context? I suppose some basic validation could occur to point out some egregious errors, but for anything that's Auth0-specific will ultimately need to hit the API for that. 

If folks still think this is still an active issue, I'm curious about the _specific_ cases in which a validation step would have been useful. OP's example of SMTP port being a specific type is one thing, but curious about others.

**Comment by willvedd** [comment]
#325 seems to be a good example of when basic validation on the YAML could have saved a headache of a situation.

**Comment by willvedd** [comment]
Folks, now that I've familiarized myself with the codebase, I'm seeing that there is actually a fair amount of configuration validation performed prior to any Auth0 API requests. While this validation certainly isn't perfect, it should catch most 

This mechanism works by validating the resource configuration files to JSON schemas defined at the API handler level. For example here's the schema for hooks:

```json
export const schema = {
  type: 'array',
  items: {
    type: 'object',
    default: [],
    properties: {
      script: {
        type: 'string',
        description: "A script that contains the hook's code",
        default: '',
      },
      name: {
        type: 'string',
        description:
          "The name of the hook. Can only contain alphanumeric characters, spaces and '-'. Can neither start nor end with '-' or spaces",
        pattern: '^[^-\\s][a-zA-Z0-9-\\s]+[^-\\s]$',
      },
      enabled: {
        type: 'boolean',
        description: 'true if the hook is active, false otherwise',
        default: false,
      },
      triggerId: {
        type: 'string',
        description: "The hooks's trigger ID",
        enum: ALLOWED_TRIGGER_IDS,
      },
      secrets: {
        type: 'object',
        description: 'List of key-value pairs containing secrets available to the hook.',
        default: {},
      },
      dependencies: {
        type: 'object',
        default: {},
        description: 'List of key-value pairs of NPM dependencies available to the hook.',
      },
    },
    required: ['script', 'name', 'triggerId'],
  },
};
```

Looking through the codebase, some schemas are defined more tightly to the API spec than others, but I'd say there's some pretty decent coverage in general.

I will be closing this ticket because it is very old and from not very actionable considering the above. However, if anyone is still running into issues that could be solved by config validation, I encourage you to open a ticket specific to your particular issue. Thanks!
