### ISSUE TITLE
Unable to import anything although import is successful 

### ISSUE THREAD

**Issue by maciej-krol** [auth0/auth0-deploy-cli#123]
Hi, 
I have configured an Application, granted it proper permissions, installed a0deploy locally. 

So far so good. 
I have managed to export all the settings from the tenant, but import does not work. 
It finds all rules/templates in the directory (lists them when importing) and finally prints "import successful", but there are no changes on the tenant. 
I have also set AUTH0_ALLOW_DELETE to true. It deleted everything, but again nothing was imported. 

Did I miss anything?

**Comment by willvedd** [comment]
@maciej-krol Were you able to resolve this issue? I'd need you to provide a sample configuration file as well as the command you used to import. It's curious to me that you notice no changes if `AUTH0_ALLOW_DELETE` is false and everything deleted if `AUTH0_ALLOW_DELETE` is true. This suggests that you're pushing an empty configuration. Can you please provide a bit more information about this issue?

**Comment by willvedd** [comment]
Appreciate you opening this issue, and apologies for how long a response has taken. However, this issue doesn't appear to be actionable from our end. We would need more specific examples of configuration you're attempting to push and the settings you configure in config.json. Further, versions released since the time of this ticket have enabled more verbose error messaging, and it's possible that updating to newer versions would reveal useful error messaging. 

If this is still an active issue for you, please feel free to open a new ticket and we can dig further into your specific issues.
