### ISSUE TITLE
Add Export/Import Hooks (Beta) ability enhancement

### ISSUE THREAD

**Issue by dextacy10-13** [auth0/auth0-deploy-cli#127]
Have been using the the auth0-deploy-cli as part of a deployment pipeline and works very well moving our config across different tenants.  However we want to make use of the 'Hooks (Beta)' functionality and be able to configure using the tenant.yaml file. If you're not already planing on adding can you look at please?

**Comment by tomsolem** [comment]
I also need this. Any updates on this request?

**Comment by vilinki** [comment]
Missing support for Hooks prevents us from using auth0-deploy-cli in our pipeline. Please, include support.

**Comment by kbrowns** [comment]
I too am blocked from automating our process because we use hooks.  

I'm seeing commit activity here related to hooks support - appears to be in the v4 code stream.  I just attempted to install a pre release of v4 auth0-deploy-cli in hopes of getting this functionality and it doesn't appear to be compatible w/ the serverside API piece of this:

```
kelly@kelly-mbp ~ % a0deploy export -c config.json -f yaml -o .
2020-01-03T17:37:07.087Z - info: Loading Auth0 Tenant Data
2020-01-03T17:37:07.088Z - info: Retrieving rules data from Auth0
2020-01-03T17:37:07.509Z - info: Retrieving rulesConfigs data from Auth0
2020-01-03T17:37:07.862Z - info: Retrieving hooks data from Auth0
2020-01-03T17:37:08.218Z - error: Problem running command export
2020-01-03T17:37:08.218Z - error: Problem loading tenant data from Auth0 APIError: {"statusCode":404,"error":"Not Found","message":"Not Found"}
kelly@kelly-mbp ~ % a0deploy --version
4.0.0-dev.21
```

Hopefully this will be coming soon, but haven't found any concrete info on this

**Comment by willvedd** [comment]
Thanks for everyone's feedback. It appears that [version 4.0.0](https://github.com/auth0/auth0-deploy-cli/tree/v4.0.0) added support to hooks so I'm opting to close this ticket. If anyone is still having issues with hooks support even after upgrading, please create a new issue so we can investigate closer.
