### ISSUE TITLE
import with "AUTH0_ALLOW_DELETE": true skips database folder, deletes user database

### ISSUE THREAD

**Issue by jameshochadel** [auth0/auth0-deploy-cli#201]
### Description

I used `a0deploy export -f directory` to export a copy of my tenant configuration, then created a `config.json` in a separate directory and set `"AUTH0_ALLOW_DELETE": true`. I then used `a0deploy import` to import the same configuration to the tenant. I expected nothing to change. Instead, the tool skipped my database folder, and deleted the users database in the tenant.

### Reproduction

Example `config.json`:

```json
{
  "AUTH0_DOMAIN": "my-domain.auth0.com",
  "AUTH0_ALLOW_DELETE": true,
  "AUTH0_KEYWORD_REPLACE_MAPPINGS": {
    "AUTH0_DOMAIN": "my-domain.auth0.com"
  },
  "AUTH0_EXCLUDED_RULES": [ "rule-1-name" ],
  "AUTH0_EXCLUDED_CLIENTS": [ "auth0-deploy-cli-extension" ]
}
```

Ran command:

```sh
a0deploy import -c tenants/my-domain/config.json -i tenants/base
```

...where `tenants/base` contained the output of the earlier directory export.

Unexpected output from this command:

```
2020-01-29T19:37:18.508Z - info: Processing directory tenants/base
2020-01-29T19:37:18.514Z - warn: Skipping database folder tenants/base/database-connections/Username-Password-Authentication as cannot find or read tenants/base/database-connections/Username-Password-Authentication/database.json
(...)
2020-01-29T19:37:27.764Z - info: Deleted [databases]: {"name":"Username-Password-Authentication","id":(omitted)}
(...)
2020-01-29T19:37:32.955Z - info: Import Successful
Success!
```

However, when I `ls tenants/base/database-connections/Username-Password-Authentication`, I see `database.json`.

I have one idea about what might have happened. My `database.json` contains this key:

```json
"enabled_clients": [
    "auth0-deploy-cli-extension",
]
```

Note in the earlier `config.json`, this client is excluded. (It did not make sense to have the CLI reconcile its own client.) Is this causing the tool to fail to read the `database.json`? And if so, perhaps the tool should have a less destructive default behavior when failing to read the file?

### Environment

- **Version of this library used:** 3.6.7
- **Version of the platform or framework used, if applicable:** auth0.com hosted
- **Other relevant versions (language, server software, OS, browser):** macOS 10.15.2
- **Other modules/plugins/libraries that might be involved:** Process is orchestrated with CircleCI, run with `circleci local execute`.

**Comment by emsearcy** [comment]
This issue is certainly giving me second thoughts about enabling AUTH0_ALLOW_DELETE!

Another idea (rather than keying off "the file exists but we excluded it for some reason"), would be for a0deploy to have an additional sanity check just for this case: when about to delete a DB when AUTH0_ALLOW_DELETE is true, if there are any users in the DB, an additional flag AUTH0_ALLOW_DELETE_DB_WITH_USERS must be set.

Or, just split out the ALLOW_DELETE to be resource specific ... ALLOW_DELETE_CLIENTS, ALLOW_DELETE_RULES, etc... (and presumably people can rest safer if they choose not to enable ALLOW_DELETE_DATABASES ;-) ). Deleting any of these other things is not nearly so disastrous as deleting a user database!
