### ISSUE TITLE
4.0.1 Export to directory fails on exporting hooks

### ISSUE THREAD

**Issue by dominicfallows** [auth0/auth0-deploy-cli#208]
### Description

When runnings an export to a directory structure, the export fails on exporting hooks

### Reproduction

Running command `a0deploy export -c config.json -f directory -o .` fails with:

```
2020-02-10T22:10:25.910Z - error: Problem running command export
2020-02-10T22:10:25.910Z - error: Problem exporting hooks
```

### Environment

- a0deploy 4.0.1
- macOS Mojave and macOS Catalina

**Comment by dominicfallows** [comment]
After an initial bit of debugging, the problem starts with the line `hook.name = hook.name || hook.id; ` in here:

https://github.com/auth0/auth0-deploy-cli/blob/d10013b262f7a744141973444fbafed86c0cea4f/src/context/directory/handlers/hooks.js#L42 

The specific hook being handling at the point of this error has the shape:

```
script: 'module.exports = function (user, context, cb) { ... }',
dependencies: {},
enabled: true,
triggerId: 'post-user-registration',
secrets: { ... },
name: undefined
```

`name` = `undefined` and there is no `id` to fallback to either.

**Comment by dominicfallows** [comment]
It works with the YAML export ok, so I will debug further into how that is handled differently, although the YAML handler has the same line `hook.name = hook.name || hook.id; 
 ` in here: https://github.com/auth0/auth0-deploy-cli/blob/d10013b262f7a744141973444fbafed86c0cea4f/src/context/yaml/handlers/hooks.js#L39 

It must be something higher up.

**Comment by dominicfallows** [comment]
Ok, so the `id` gets stripped out by `this.assets = stripIdentifiers(auth0, this.assets);` in both directory and YAML exports:

Directory export:
https://github.com/auth0/auth0-deploy-cli/blob/f6b613bdac8ce03716d82b0597d76a0c76705526/src/context/directory/index.js#L71

YAML export:
https://github.com/auth0/auth0-deploy-cli/blob/f6b613bdac8ce03716d82b0597d76a0c76705526/src/context/yaml/index.js#L112

Any reason why it would need to strip hooks ids?

**Comment by blortfish** [comment]
@dominicfallows I ran into a similar issue. I think this might be a problem for hooks created a while ago. The name property was missing on my hooks, possibly because there was no option to name hooks back when they were created.

I was able to fix this by grabbing my hooks from the management api and assigning each of them a `name` property using https://auth0.com/docs/api/management/v2#!/Hooks/patch_hooks_by_id.

Not sure if this helps you, but figured i'd drop this here for anyone experiencing similar problems.

**Comment by skjolber** [comment]
Cloning the hook and deleting the old also had the same effect as using the `patch_hooks_by_id`. Using `AUTH0_EXPORT_IDENTIFIERS` in export will [block import](https://github.com/auth0/auth0-deploy-cli/blob/bc311a731005a9a8eb1720016da497919b96bbf5/examples/directory/README.md#example-export).

**Comment by MichaelBuhler** [comment]
I encountered this error today. The workaround certainly exists. For me, I was able to rename the hook in the GUI to populate the name field, and then dumping working fine. There should be a check, warning, and skip between lines 42 and 43 for unnamed hooks when identifiers are stripped.

**Comment by willvedd** [comment]
@MichaelBuhler Are you able to indicate wether or not this is still an active issue for you?

**Comment by MichaelBuhler** [comment]
@willvedd I no longer work on that project. But, as I mentioned, using the Auth0 UI to name the hook eliminates this error. I don't know if this repo still errors on dumping unnamed hooks.

**Comment by willvedd** [comment]
@MichaelBuhler thanks for the feedback.

Folks, I'm opting to close this ticket because it's fairly old and I don't believe this is an active issue. Apologies for the delayed response, it should have gotten more attention earlier. If anyone here is still experiencing this issue please feel free to open a new ticket and we can help you work through your specific issues together.
