### ISSUE TITLE
callback_domain empty in email template

### ISSUE THREAD

**Issue by StevenVerbiest** [auth0/auth0-deploy-cli#233]
I'm trying to use the `{{ application.callback_domain }}` variable in an email template, but this returns an empty string. 

I'm using the latest version (3.4). 
My mappings are set up like this:

```
{
  "APP_HOST": "https://test.<domain>,
  "APP_HOSTS": [
    "https://test.<domain>,
    "http://localhost:3000"
  ],
  "APP_CALLBACKS": [
    "https://test.<domain>",
    "http://localhost:3000"
  ],
}
```
and my `clients/<appname>.json` is something like this (I omitted some settings):

```
{
  "allowed_clients": [],
  "allowed_logout_urls": @@APP_HOSTS@@,
  "allowed_origins": @@APP_HOSTS@@,
  "app_type": "spa",
  "callbacks": @@APP_CALLBACKS@@,
  "cross_origin_auth": false,
  "is_token_endpoint_ip_header_trusted": false,
  "mobile": null,
  "oidc_conformant": true,
  "token_endpoint_auth_method": "none",
  "web_origins": @@APP_HOSTS@@,
  "client_aliases": [],
  "cross_origin_loc": null
}
```

Is this a bug or am I doing something wrong?

**Comment by willvedd** [comment]
@StevenVerbiest Thanks for opening this ticket and sorry for the lengthy delay. 

Am I understanding you correctly that you're attempting to apply keyword replacements directly to your email templates? Because you reported this on a much older version, my first recommendation is to update because it does appear to be possible through the code. You could also try injecting the keyword replacements directly into the template, if that is an appropriate solution for you. 

Further, do you still consider this to be an open issue or were you able to find a suitable workaround?

**Comment by willvedd** [comment]
Closing now because I don't believe this to be actionable but happy to open if more context provided.
