### ISSUE TITLE
version 5.0.0 fails on directory import with Payload validation error

### ISSUE THREAD

**Issue by dmetzgar** [auth0/auth0-deploy-cli#255]
### Description

On running a directory import with a directory that used to work prior to v5, we get a failure with the following error:
```
error: Problem running command import during stage processChanges when processing type pages
error: Payload validation error: 'Additional properties not allowed: url' on property change_password (Change Password page customization).
```

There is no change_password property anywhere in our directory.

### Reproduction

Our directory only includes emails, rules, and pages. Allow deletes is turned off.

### Environment

Using latest version 5.0.0.

**Comment by simoncaley** [comment]
I have just hit this exact issues earlier today and have been unable to resolve it.
Same details as @dmetzgar and for an additional note - was using the exact deployment process yesterday and worked fine (about 20 hours ago)

**Comment by robbiemccorkell** [comment]
Same issue here, my pipelines are failing as of this morning and no change has been made in this area.

Even stranger is that running the a0deploy CLI locally works fine for me, but this failure always occurs when running within a Github actions runner

**Comment by rynecheow** [comment]
Facing this issue as well on PSaaS tenants. Doesn't work for me on either on both local and CI. No change was made to the deployment configuration since then. 

Can we get some help here? @shawnmclean

**Comment by danarielpoblete** [comment]
Same issue here, pipelines are failing but there was no change made in our code.

Not sure what change was made in the Management API.

Please help, thanks.

**Comment by dandenton** [comment]
We've successfully deployed using Auth0 Deploy CLI v 5.0.0 on June 30th but the same release fails as of today.  I'm guessing it's not the CLI tool itself but the API that it's using.

**Comment by rynecheow** [comment]
See that a fix has been merged in the Auth0 source code extension tools repo - any chance of knowing when will this fix be released? As our CI/CD pipes are still failing - any workaround at the moment?

**Comment by pmalouin** [comment]
@rynecheow 

We're preparing the release for today. Sorry for the delay.

**Comment by pmalouin** [comment]
The issue was fixed by the newest version of auth0-source-control-extensions (https://github.com/auth0-extensions/auth0-source-control-extension-tools/releases/tag/v4.1.1). Please re-install the auth0-deploy-cli and it will automatically pull the patched version of auth0-source-control-extensions.

We're sorry for the inconvenience 🙏

**Comment by rynecheow** [comment]
Thanks @pmalouin and @shawnmclean for the action :)

**Comment by scottkimGit** [comment]
Hi, after installing a patched version, I no longer get **Payload validation error**, however, a different error message started shown. The import process doesn't even begin:
`$ a0deploy import -c ./config.dev.json -i ./test/tenant.yaml
2020-07-07T21:08:39.105Z - error: Problem running command import
2020-07-07T21:08:39.106Z - error: Schema validation failed loading [
    {
        "keyword": "type",
        "dataPath": ".guardianPolicies",
        "schemaPath": "#/properties/guardianPolicies/type",
        "params": {
            "type": "object"
        },
        "message": "should be object"
    }
]`

**Comment by pmalouin** [comment]
@scottkimGit Can you please tell me if you have a value in your `./test/tenant.yaml` file for the attribute named `guardianPolicies`?

If it's set, you can remove it and see it if passed.
If it's an array, you can change it to a nested object something like:
```
guardianPolicies:
  policies: []
```
or
```
guardianPolicies:
  policies:
    - all-applications
```

**Comment by scottkimGit** [comment]
It was set as `policies: []` and updated to the object format and it passes now. Thank you for a quick response.

**Comment by pmalouin** [comment]
Thanks for confirming 🙇 

Here are a little bit more details and how we are preventing these issues to occur again. This project (auth0-deploy-cli) currently has a dependency on [auth0-source-control-extension-tools](https://github.com/auth0-extensions/auth0-source-control-extension-tools/). The version specifier is currently set to `^4.0.7`:

https://github.com/auth0/auth0-deploy-cli/blob/a6c762addc38e002880419c13c07de434ac3e9e3/package.json#L32

In practice, this means that installing auth0-deploy-cli will pull the latest version of auth0-source-control-extension-tools (including minor bumps). Because we follow semantic versioning, it becomes problematic when we ship new features (minor bumps) to that project and auth0-deploy-cli immediately starts pulling these features. auth0-deploy-cli needs to implement the corresponding handlers for these new features or otherwise we face unexpected conditions like here.

As a measure to solve these kinds of issues in the future, we are switching to using tilde-matching for the version specifier, which will only pull patch-level upgrades to the library. See: https://github.com/auth0/auth0-deploy-cli/pull/252#discussion_r450471794

Thanks again for the report and sorry for the inconvenience

**Comment by sdmcintyre** [comment]
This issue is resolved for me now, thanks.
