### ISSUE TITLE
exit code of 0 is returned even on error

### ISSUE THREAD

**Issue by adrian-skybaker** [auth0/auth0-deploy-cli#272]
### Description

Loading auth0-deploy-cli module breaks default unhandled exception handler, and exit code of 0 is returned even on error.

### Reproduction

deploy.js:
```
const a0cli = require('auth0-deploy-cli');
nonexistentFunc();
```
package.json:
```
{
  "dependencies": {
    "auth0-deploy-cli": "^5.1.5"
  }
}
```

```
npm install
node deploy.js
echo $?
```

### Environment

node v13.13.0
auth0-deploy-cli 5.1.5

**Comment by willvedd** [comment]
To be clear, as this wasn't immediately obvious to me when investigating, this issue is specific when importing this package as a node module. This is as opposed to executing via the CLI, which _does_ exit with non-zero codes when incurring an error. 

I'd actually even go a step further and say that exiting the process from the package is overly patronizing and may actually lead to unpredictable behavior. For example, consider the following:

```js
const a0cli = require('auth0-deploy-cli');

(async()=>{
    try {
        await a0cli.import()
    } catch (err) {
        console.error(`Auth0 failed to deploy: ${err}`)
    }
    //... other CI operations that you may still want to run afterwards
})()
```
In the above example, pretend this is your CI script that executes several commands from this script. If this package exited with any code, none of the lines after `await a0cli.import()` would execute. And even worse, the error wouldn't be caught so you wouldn't see any error printed out. This is why you rarely see npm packages exiting without a very good reason, because it interferes with the logical flow of your applications.

As for the spirit of this issue, I'd recommend using this packages as a CLI if possible. And if that doesn't suit your needs, you'd need to implement your own exit codes as you require. It might looks something like this:

```js
const a0cli = require('auth0-deploy-cli');

(async()=>{
    try {
        await a0cli.import() // Remember that this is async!
        //... other relevant script functionality
    } catch (err) {
        console.error(`Some error occurred:  ${err}`)
        process.exit(1)
    }
})()
```
I'm going to mark as wontfix, but open to feedback.
