### ISSUE TITLE
Webpack Support

### ISSUE THREAD

**Issue by NotMyself** [auth0/auth0-deploy-cli#362]
### Description

> The main entry point of the cli exports functions that can be used directly. When importing this package into a project using webpack to build, it fails to load because of the shebang in the first line of the file.

### Reproduction

> Import package into any project that uses webpack to build.

![Screen Shot 2021-06-24 at 8 28 26 AM](https://user-images.githubusercontent.com/73120/123290475-2be56880-d4c6-11eb-8966-b05d297f0cba.png)

### Environment

> Please provide the following:

- **Version of this library used:** v7.1.1
- **Version of the platform or framework used, if applicable:** vscode extension
- **Other relevant versions (language, server software, OS, browser):**
- **Other modules/plugins/libraries that might be involved:** webpack

### Workaround

I was able to work around this by adding the string-replacement-loader dependency and adding the following rule to my webpack.config.js.

```js
module: {
    rules: [
      // allows the cli to be webpacked
      {
        test: path.resolve(
          __dirname,
          'node_modules/auth0-deploy-cli/lib/index.js'
        ),
        loader: 'string-replace-loader',
        options: {
          search: '#!/usr/bin/env node',
          replace: '',
        },
      }
    ]
  }

```

**Comment by willvedd** [comment]
Hi @NotMyself, appreciate you opening this ticket. Apologies that it has taken a while to respond.

Bundling this application with webpack suggests to me that this library is being introduced as a dependency within a larger application with a frontend, perhaps even a SPA that runs in the browser. Assuming that my suspicions are correct, I do not recommend doing this as it goes against the spirit of the tool, which is primarily to be a standalone tool to help manage configuration within developer workflows. Maintaining native CLI support here is critical for this project; the node module exports are primarily enable more complex expressions with node scripts. 

Nonetheless, if bundling is still desired, the provided workaround that you have above seems to be straightforward enough. And, FWIW, the Typescript compiler does bundle the Deploy CLI without any issues, so that may be an option for you. 

At this current point in time though, I do not see us realistically prioritizing this feature for development, especially since your workaround exists.
