### ISSUE TITLE
Getting an error : Global limit has been reached

### ISSUE THREAD

**Issue by antham** [auth0/auth0-deploy-cli#386]
### Description

When I run the tool, I get this error from the logs :  
```{
  "date": "2021-10-13T06:38:19.312Z",
  "type": "api_limit",
  "description": "Global limit has been reached",
  "client_id": "xxxx",
  "client_name": "",
  "details": {
    "request": {
      "method": "put",
      "path": "/api/v2/rules-configs/{key}"
    },
    "response": {}
  },
  "log_id": "xxxx",
  "_id": "xxxx",
  "isMobile": false,
  "user_agent": "Other 0.0.0 / Other 0.0.0"
}
```
The deployment seems to work without any problem though.

### Reproduction

Simply running the tool, the whole deployed config is made from a dump with this tool.

### Environment

auth0-deploy-cli : `7.3.1`

**Comment by willvedd** [comment]
@antham Are you running against a free-tiered tenant? Those tenants have tighter API limits and commonly affects this utility, see: #200 #340 #33 .

**Comment by antham** [comment]
Hi,
I can't remember from where I picked this log exactly, but it was on one of our environment tied to a paid environment, I will check.

**Comment by willvedd** [comment]
@antham Thanks for opening this issue. Assuming this was on a paid tenant, I still consider this to be similar to #200 #340 and #33 because it's a limit enforced at the API level and this tool should have a method of working within the bounds of those limits. I still do find it odd though that you're running against this limit for no seemingly obvious reason. 

If this is still an active issue for you, I invite you to create a new issue so we can discuss your individual circumstances in more detail.

**Comment by antham** [comment]
Ok right, I will do it if needed.
