### ISSUE TITLE
Problem loading tenant data from Auth0 Unauthorized: Bad audience

### ISSUE THREAD

**Issue by rcauquil** [auth0/auth0-deploy-cli#389]
I was trying to export my tenant config after updating node to 16.13.0 using a0deploy v7.3.1 and was facing the following issue:

> Problem loading tenant data from Auth0 Unauthorized: Bad audience

This has been solved by rolling back to node 14.16.1 using a0deploy v7.1.1

Is this a misonfiguration on my side or a bug in yours ?

**Comment by willvedd** [comment]
@rcauquil Thanks for opening this. Can you indicate if this still an active issue? This error is being generated by the API so unlikely to be caused by a different node version. My guess is that a breaking change may have been introduced between 7.1.1 and 7.3.1 when paired with your specific configuration. It would help if you were able to provide a sample configuration that triggers this exact error.

**Comment by rcauquil** [comment]
@willvedd yes still an issue I have upgraded to 7.3.7 on both previous node version, I had to rollback again for 7.1.1 on 14.16.1 to be able to export my tenant settings
