### ISSUE TITLE
Get AUTH0_EXCLUDED_DEFAULTS documented

### ISSUE THREAD

**Issue by stuarthadfieldglobality** [auth0/auth0-deploy-cli#392]
Hey folks,

Is there any way we could document [this](https://github.com/auth0/auth0-deploy-cli/pull/236) in the official docs: https://auth0.com/docs/deploy/deploy-cli-tool?

It's really only cited in the two "demo config files" with no real explanation of what it does.

It's also curious that email providers are the only entity that _by default_ export & expect placeholders for secret config values (or at least, that's what it seems like to me)

### Describe the ideal solution

Ideally the export of email providers & their secrets would be documented, and the functionality of AUTH0_EXCLUDED_DEFAULTS is explained.

**Comment by willvedd** [comment]
This is a very good question! Frankly, I myself have the same questions around the `AUTH0_EXCLUDED_DEFAULTS`  configuration property. And I too find it odd that it's only implemented in the email provider. 

My theory is that it was an abstraction that was implemented at one point to solve an issue but there have since been redundant mechanisms to accomplish the same thing. Particularly, I would expect sensitive properties to be excludes/obfuscated by default and if not, the `EXCLUDED_PROPS` configuration property exists to specify those exclusions with more precision.

Despite this configuration property existing, I intentionally do not plan to document this property. It is not clear, it doesn't solve any obvious use case and really has only been a source of confusion. I expect it to remain in the code to prevent any type of breaking changes that may occur, but I will also be generally dissuading folks from using it unless new information comes to light about it. I hope everyone understands this stance. 

However, I'd like to remind everyone that if there is a particular use case that a new configuration property may solve, please feel empowered to work with your account managers or open a Github ticket so we can evaluate appropriately. Thanks!

**Comment by stuarthadfieldglobality** [comment]
Sure, thanks for the response @willvedd!

Appreciate all the work you're doing with this tool 🙏
