### ISSUE TITLE
Custom database scripts are no longer deployed automatically from files

### ISSUE THREAD

**Issue by provegard** [auth0/auth0-deploy-cli#398]
### Description

Version 7.3.0 broke reading of custom database scripts. Previously we just put the database scripts (`get_user.js` and `login.js`) next to `database.json` and the the deploy tool would automatically pick them up and put them in `options.customScripts`.

Since https://github.com/auth0/auth0-deploy-cli/commit/d33413a789864af1ae345ef5debac0e24111d3ff, the deploy code requires `options.customScripts` to be populated prior to the deploy.

This caused a production outage since our custom scripts were not deployed, meaning that the default scripts were used instead.

We have fixed the problem on our end by populating `options.customScripts` in the build pipeline, so this is no longer a problem.

However, it might be a good idea to mark this as a breaking change and/or describe it in the migration guide.

### Reproduction

Make a deploy with empty `options.customScripts` and with the script files next to `database.json`.

### Environment

- **Version of this library used:** auth0-deploy-cli 7.3.2, auth0 2.37.0
- **Version of the platform or framework used, if applicable:** not relevant
- **Other relevant versions (language, server software, OS, browser):** not relevant
- **Other modules/plugins/libraries that might be involved:** not relevant

**Comment by willvedd** [comment]
First of all, on behalf of the team, I extend apologies for the breaking change. In retrospect, that commit should have had more consideration for backwards compatibility. Now that we have more dedicated resources for this and other tooling projects, we're able to have more accountability and support for these types of issues that pop up. And further, we're trying to get better at preventing breaking changes.

For this specific case, I can see why the change was added. The flexibility that was provided will mean a more expressive and sustainable way of managing configuration files going forward. That's not to fully justify a breaking change, but just a reason why I don't see us providing any retroactive fix here. 

I'm going to close because there's nothing actionable here, however I'd like to again acknowledge that your issue was indeed valid and unfortunate.
