### ISSUE TITLE
Allow renaming organizations

### ISSUE THREAD

**Issue by nancyhabecker** [auth0/auth0-deploy-cli#440]
### Describe the problem you'd like to have solved

The ability to rename existing organizations through `a0deploy`.

### Describe the ideal solution

I have an Auth0 organization (name=`test1`, id=`org_123`) and I would like to rename it with the `auth0-deploy-cli`.

I have the following in my `tenant.yaml` file.
```
organizations:
  - name: test1a # was test1
    id: org_123
    connections:
      - name: mydb
        assign_membership_on_login: false
    display_name: Test 1
```

The current behavior is an error.

```
2022-03-10T19:42:09.651Z - error: Problem running command import during stage processChanges when processing type organizations
2022-03-10T19:42:09.652Z - error: Problem updating organizations {"id":"org_abc,"name":"test1a","connections":[{"assign_membership_on_login":false,"connection_id":"con_def"}],"display_name":"Test 1"}
TypeError: Cannot destructure property 'connections' of '(intermediate value)' as it is undefined.
```

I am running `7.5.0`.

### Alternatives and current work-arounds

I can rename it through the Auth0 UI or the Management API (https://auth0.com/docs/api/management/v2#!/Organizations/patch_organizations_by_id) and then update my `tenant.yaml` file with the new name.

### Additional context

I believe this is the line it's breaking on. https://github.com/auth0/auth0-deploy-cli/blob/99fe955c31e6d99c88c64a3992c610b9b7113395/src/tools/auth0/handlers/organizations.js#L87

**Comment by willvedd** [comment]
Appreciate the thought-out ticket. I agree that this seems like something that should be possible but by default resources do not have IDs exported, so matching on name is something that occurs fairly frequently in the codebase. My best explanation for why IDs aren't exported is because the configuration should really be agnostic of tenant and IDs are specific to a particular resource. Doing so enables being able to apply configurations to any number of tenants, think: dev, stage, prod. 

Granted, in the context of single-tenant management, having IDs makes sense and it should be easy enough to use them when possible, but ignore otherwise. I suppose there's no harm in this, but adding this functionality to just organizations seems a bit incomplete, I'd want to apply to all resource types. 

But now that I think about this further, I feel like this could work if a new organization is created with the update name and the "old" organization deleted, but I'm unsure if that approach would be too heavy handed. All this to say that selecting resources on both ID and name is a bit trickier than it might first appear. And unfortunately, I cannot think of a workaround for you at this time.

**Comment by nancyhabecker** [comment]
>adding this functionality to just organizations seems a bit incomplete, I'd want to apply to all resource types.

That would be amazing. FWIW, it appears that clients can be renamed if `client_id` is included in the configuration.....

Yes, the current behavior if I rename an organization via `a0deploy` is that it creates a new one and deletes the old one, but unfortunately that generates a new ID so I need to update our client with that ID.

For now, we will rename through the Auth0 UI and update the tenant config (or possibly manage organizations outside of `a0deploy`).

**Comment by willvedd** [comment]
Thanks for being patient with this request. Now that I'm more familiar with the Deploy CLI and its modus operandi, I feel more capable to weigh in on this. First, I think this request is reasonable, especially if needing to manage a large number of organizations. And like I mention above, you could easily apply this same requirement to other named Auth0 resources. 

However, the Deploy CLI at it's core is a tool to help facilitate multi-tenant development. It is only able to facilitate that by ignoring IDs and instead using names as a method of identifying resources across tenants. Otherwise, the tool would need to maintain state to understand which resources mapped to which ID. Which leads into a second (and admitted unwritten) principle, which is that the Deploy CLI is relatively stateless. Besides the resource configuration, no other input is required into the system for managing resources. This is in contrast to the [Terraform Provider](https://github.com/auth0/terraform-provider-auth0) which maintains a mapping of resource IDs in a state file. This mapping of ID to resource is seamless when creating one, however for existing resources, you need to manually provide the ID to establish that mapping. One of the tradeoffs of being stateless is relying on names to be static and unique, which for most folks is reasonable in order to not need to keep track of IDs.

Of course, it would be completely possible to export IDs and establish a preference of an ID if it is present, otherwise default to the name. However, that would be a large lift that wouldn't afford much besides unlocking the ability to rename resources. Especially given the small team that we have an a mountain of competing priorities, I'm afraid to say that we would probably never get to it.

However, despite the above, I offer you two suggestions for accomplishing the original request:
- Update the organization's display name. I can see this accomplishing most business-facing needs as long as you can deal with misnamed things on the backend.
- Explore the [Auth0 Terraform Provider ](https://github.com/auth0/terraform-provider-auth0). You're even welcomed to use it in tandem with the Deploy CLI, ignoring organizations in Deploy CLI and managing them through Terraform instead. A bit heavy handed but would work in theory.
