### ISSUE TITLE
Add custom domains to this tool

### ISSUE THREAD

**Issue by sreeramjayan** [auth0/auth0-deploy-cli#443]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Your attention to detail here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

> auth0-deploy-cli currently doesn't support custom domains. Has this feature been prioritized? If not, are you'll open to outside contributions to add this functionality?

### Describe the ideal solution

> auth0-deploy-cli supports importing/exporting custom domains.

## Alternatives and current work-arounds

> Custom domains can be updated manually through the UI.

**Comment by sreeramjayan** [comment]
Thank you.

**Comment by willvedd** [comment]
@sreeramjayan Good news, custom domains support has been added in [v7.12.0](https://github.com/auth0/auth0-deploy-cli/releases/tag/v7.12.0). Please note that at this time, custom domains can only be added and deleted, but not updated. I don't expect this to be a hangup for most folks because there are only a couple of niche properties that can be updated on custom domains once created.
