### ISSUE TITLE
Control over Role ID

### ISSUE THREAD

**Issue by SeanFeldman** [auth0/auth0-deploy-cli#449]
### Describe the problem you'd like to have solved

When replicating environments, I understand that IDs are not replicated for the object that is tenant-specific. For example, users or clients. But roles are somewhat different. Roles are identical between tenants (environments) and need to be the same across all tenants (dev, test, uat, prod). Unfortunately, when trying to import `roles`, its IDs are not propagated. And since there's no way to specify an ID when creating roles, it means role IDs are different between environments and there's no way to refer to a specific role by its ID.

### Describe the ideal solution

Either allow importing role ID or providing the ID upon creation.

## Alternatives and current workarounds

The alternative is not ideal. Searching for a role ID by the role name, hopefully, that doesn't change at some point, causing the system to fail if a role was renamed.

### Additional context

I [asked a question](https://community.auth0.com/t/import-export-of-role-ids-between-tenants/80173) for a possible workaround on the forum in case someone is looking for this information.

**Comment by willvedd** [comment]
Thanks for opening this ticket.

>Roles are identical between tenants (environments) and need to be the same across all tenants (dev, test, uat, prod).

Can you explain this a bit further? I don't believe this is true. Assuming you have a completely different tenant for each environment, the IDs, AFAIK, would be different across all. 

The Deploy CLI is basically a wrapper around the Auth0 Management API, it is beholden to its functionality. Looking at the [Auth0 Management API](https://auth0.com/docs/api/management/v2#!/Roles/post_roles), ID is not a definable field. 

While I do agree that matching on name is not ideal, there is no alternative currently. I generally wouldn't advise changing the name of a role anyway, doing so suggests some type of repurposing, which may cause confusion amongst the organization.

**Comment by SeanFeldman** [comment]
> Can you explain this a bit further? I don't believe this is true. Assuming you have a completely different tenant for each environment, the IDs, AFAIK, would be different across all.

The system I'm building has to manage users within the application rather than via Auth0 portal. When listing all users in a given role, I'm going through the Management API, Roles object to retrieve all users assigned the role. The only option I have to pass is the role ID. There's no option to pass a role name.
![image](https://user-images.githubusercontent.com/1309622/159359474-97679b9e-41f8-4c6c-bdd0-8624f23c3e6b.png)

No matter what tenant is, the functionality is the same for dev/test/uat/production. To be able to query users by the role, I need something that is consistently representing the roles in these environments. Role ID would be that but it's not possible to create a role with a specified ID.

Matching on name is not ideal but I don't see an option how to query for all the users by the role name either.
The alternative would be a workaround to keep role name/ID mapping per environment(tenant) in a configuration file but that feels unnecessary given that the role will be identical for all tenants.

Does that describe the problem better, @willvedd?

**Comment by SeanFeldman** [comment]
Just to add to my previous comment: REST API for both, [Get Role's Users](https://auth0.com/docs/api/management/v2#!/Roles/get_role_user) and [Assign Users to a Role](https://auth0.com/docs/api/management/v2#!/Roles/post_role_users) only accept role id. Therefore having a consistent role ID between tenants would make sense.

**Comment by willvedd** [comment]
Ok yes, I think I understand a bit more. Your main challenge is that the role names and _only_ their names remain rigid across all your tenants. Your application, being agnostic of tenant, needs to assign roles to users. Your dilemma is that IDs are not user-defined nor is the role-name directly useable for API queries. Your proposed solution is to assign a static role ID through the Deploy CLI so that your application has a consistent and predictable identifier to pass into Management API calls. 

This repo, the Deploy CLI is only concerned with the management of tenant configuration. For your application, you're using it to sync configuration between your different environments. However, we're still beholden to the limits of the Management API, and for better or worse, you cannot define IDs for roles. In fact, I don't believe you can define IDs for most (or all) resource types. 

Having consistent role IDs across tenants, while fixing your use case, wouldn't make them true IDs and I assume would violate some backend uniqueness constraints. All this to say I don't think this could be fixed through configuration management.

However, in your case, I think this could be solved by doing an initial GET request for all roles, iterate through those roles matching by name so you can determine the ID. From there you can use that ID to make your Management API calls. If you're worried about the performance of adding another API call to your chain, you can add a step in your build process to create a cache that matches specific environment roles to their respective role ID. 

Hope that helps!

**Comment by SeanFeldman** [comment]
I understand the constraints of a multi-tenant system regarding the IDs and the fact that the Deploy CLI tool relies on it and cannot drive a significant change.

A GET request to fetch and map all the roles is unnecessary in a system where those roles are static and known up-front. Instead, a configuration per environment where each role ID is preconfigured would be a simpler and more efficient solution.

I appreciate the time you've invested in answering my comments.
