### ISSUE TITLE
a0deploy import fails to create new rule

### ISSUE THREAD

**Issue by VincentLandais** [auth0/auth0-deploy-cli#522]
### Description

In my project I have 3 tenants (dev, staging, prod). On the dev online console I created a new rule based on the email domain whitelist template. I exported the configuration locally with a0deploy, made some changes to the function, and then I tried to import the new rule to my staging tenant but got this error:
```
2022-04-29T09:01:52.925Z - info: Getting access token for ****
2022-04-29T09:01:53.088Z - error: Problem running command import during stage processChanges when processing type rules
2022-04-29T09:01:53.088Z - error: this.client.updateRule is not a function
```
To fix this issue I had to manually create a rule with the same name on my staging tenant, then run the same `a0deploy import` command.

The expected behavior would have been the rule to be automatically created in my staging tenant by the cli.

### Reproduction

- Create 2 tenants `A` and `B`
- Create a new rule in tenant `A`
- Export `A`'s configuration locally with `a0deploy export`
- Import the local configuration to `B` with `a0deploy import`

Screenshot of the error:
<img width="850" alt="image" src="https://user-images.githubusercontent.com/100678450/165924131-6769d58c-69d3-46d8-bed2-0cf486dc889e.png">

### Environment

- a0deploy version 7.9.0, tested with 7.10.0 too

**Comment by travispeloton** [comment]
@willvedd we are also seeing this problem. We pinned to version 7.7.0 and are no longer seeing the problem.

**Comment by willvedd** [comment]
Thanks for reporting this. I think I've found the issue, it looks like the `updateRule` alias isn't being found on the Auth0 API client. Odd, because it does actually exist, but I believe there's something about how the Deploy CLI initializes the client that causes this behavior. Anyway, it works if you use the manager alias: `this.client.rules.update`. I have a PR up for fixing it: https://github.com/auth0/auth0-deploy-cli/pull/526 have verified that it works locally. Should be able to have it out in the next couple days or so.
