### ISSUE TITLE
Export command error: getaddrinfo EAI_AGAIN null

### ISSUE THREAD

**Issue by Luca8991** [auth0/auth0-deploy-cli#529]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

When executing:
```
a0deploy export --debug --format directory --config_file config.json --output_folder .
```
I get the error:
```
2022-05-04T16:17:51.079Z - error: Problem running command export
2022-05-04T16:17:51.080Z - error: getaddrinfo EAI_AGAIN null
```

**N.B.:** What's really strange is that, with the exact same configuration, the **import** command works perfectly!

### Reproduction

- created `config.json` as explained at [Configure the Deploy CLI Tool](https://auth0.com/docs/deploy-monitor/deploy-cli-tool/install-and-configure-the-deploy-cli-tool#configure-the-deploy-cli-tool)
- run
  ```
  a0deploy export --debug --format directory --config_file config.json --output_folder .
  ```
- get the error

### Environment

- **Version of this library used:** 7.3.7
- **Version of the platform or framework used, if applicable:**
- **Other relevant versions (language, server software, OS, browser):** Ubuntu 20.04.4 LTS 64 bit
- **Other modules/plugins/libraries that might be involved:**

**Comment by willvedd** [comment]
The `getaddrinfo EAI_AGAIN null` error emits from the OS level.  Referencing the [man7 linux manual](https://man7.org/linux/man-pages/man3/getaddrinfo.3.html#RETURN_VALUE) provides a bit more context:

> EAI_AGAIN
>               The name server returned a temporary failure indication.
>               Try again later.

I'm assuming that you're running this in a container? If so I'd look to make sure that you've appropriately configured your network settings. It's odd that it works for import, though, I'd look to see that you have both stages configured the same. Or perhaps the issue is truly intermittent and stemming from somewhere in the DNS lookup chain.

**Comment by Luca8991** [comment]
I found the problem.
I was using environment variables in my `config.json` file like this:
```
{
  "AUTH0_DOMAIN": "##AUTH0_DOMAIN##",
  "AUTH0_CLIENT_ID": "##AUTH0_CLIENT_ID##",
  "AUTH0_CLIENT_SECRET": "##AUTH0_CLIENT_SECRET##",
  "AUTH0_ALLOW_DELETE": false,
}
```
and running the command
```
a0deploy export --debug --format directory --config_file config.json --output_folder .
```
did not parse the environment variables, even if here
https://github.com/auth0/auth0-deploy-cli/blob/49a355e8af0ef79cfc697dccb765d80f2ae61bc0/src/args.ts#L62
the default value is `true`.

I found out that running the command specifying `--env=true` works:
```
a0deploy export --debug --env=true --format directory --config_file config.json --output_folder .
```

The weird thing is that running the **import** command works even without `--env=true` flag.

**Comment by willvedd** [comment]
Ok great I'm glad you figured it out. If you intend to pass in environment variables for the authentication details, I advise you to explicitly enable that with the `--env=true` flag for both import and export. You also do not need to create the environment variable mapping in the `config.json` file. Instead, you can omit entirely and the tool will automatically apply those environment variables. Example:

**config.json**
```json
{
  "AUTH0_ALLOW_DELETE": false
}
````

```shell
AUTH0_DOMAIN=<your domain> AUTH0_CLIENT_SECRET=<your client secret> AUTH0_CLIENT_ID=<your client ID> a0deploy export --env=true --output_folder=local --format=directory -c=config.json
```

>The weird thing is that running the import command works even without --env=true flag.

This is because the env flag defaults to true for the import command whereas it defaults to false for export. I know it sounds absurd, but this was just the result of maintaining backwards compatibility and poor forward thinking. I intend to solve this in the next major release, but no timetable on that.

**Comment by willvedd** [comment]
@Luca8991 Thanks for opening this ticket. I can understand how you triggered this bug and would like to prevent it from happening to other folks in the future. We're in the process of revamping our documentation so my hope is to make it more clear about how to inject environment variables and leverage the keyword mappings. However, because you were able to resolve this ticket and there are no other action items, I'm opting to close this ticket.
