### ISSUE TITLE
Getting clientGrants with audiences that do not correspond to an API when exporting

### ISSUE THREAD

**Issue by giomaik** [auth0/auth0-deploy-cli#59]
Hello,

I am using the tool to export an existing tenant configuration from an instance using the appliance deployment model, but when I try to import this configuration to another tenant, I get a few errors because some client grants use an audience that does not match any identifier. The errors look like `Not Found: No resource with identifier https://foo/bar/`
I am aware of issue #29 but that is not my case as it is not the Management API those grants are targeting. Manually inspecting the tenant APIs also did not reveal any API using that audience either. My understanding is that clientGrants could only be created against an existing API. So I am unsure how/why those grants get exported. Could it happen that the API was removed but not the grants targeting it? And in that case, would I be safe in removing the offending clientGrants?

Thanks.

**Comment by zzbennett** [comment]
I'm experiencing the same issue. Create an application and API in one of my tenants, exported the configuration using auth0-deploy-cli and copied the configs to another tenant. The configs are exactly the same as what was exported except I changed the CUSTOM_DOMAIN (because the other tenant has a different custom domain), and I removed the `id` from the grant file. Now I cannot import the configuration. The error I see is:
```
2020-03-12T20:19:34.291Z - error: Problem running command import during stage processChanges when processing type clientGrants
2020-03-12T20:19:34.291Z - error: Problem creating clientGrants {"client_id":"<CLIENT_ID>","audience":"https://<CUSTOM_DOMAIN>/password_verifier"}
Not Found: No resource with identifier https://<CUSTOM_DOMAIN>/password_verifier
```

I'm uploading a grant that looks like this:
```
{
  "client_id": "CCloud Password Verifier",
  "audience": "https://<CUSTOM_DOMAIN>/password_verifier",
  "scope": []
}
```

Client looks like this:
```
{
  "is_token_endpoint_ip_header_trusted": false,
  "name": "CCloud Password Verifier",
  "is_first_party": true,
  "oidc_conformant": true,
  "sso_disabled": false,
  "cross_origin_auth": false,
  "allowed_clients": [],
  "callbacks": [],
  "native_social_login": {
    "apple": {
      "enabled": false
    },
    "facebook": {
      "enabled": false
    }
  },
  "jwt_configuration": {
    "alg": "RS256",
    "lifetime_in_seconds": 36000,
    "secret_encoded": false
  },
  "client_aliases": [],
  "token_endpoint_auth_method": "client_secret_post",
  "app_type": "non_interactive",
  "grant_types": [
    "http://auth0.com/oauth/grant-type/password-realm"
  ],
  "custom_login_page_on": true
}
```

I think the export is leaving out something important that is needed by the import. API and Client are working correctly in the tenant where I set it up via the UI, but I cannot export those configs now to my other tenants.

**Comment by willvedd** [comment]
@giomaik @zzbennett Do either of you believe this is still an active issue?

**Comment by willvedd** [comment]
Apologies for the delayed response, this appears to have been a bug at one point. Though I don't have reason to believe that it's an issue that affects more recent versions. So for that reason, I'm closing this ticket. If this is indeed an active issue for anyone, I invite you to create a new issue and we can help assist.
