### ISSUE TITLE
Rules exporting with ID's

### ISSUE THREAD

**Issue by matt-filion** [auth0/auth0-deploy-cli#60]
Its a bit unclear how these should be handled. I understand the value in the ID being present, in terms of what the tool needs, but the exported YAML or JSON having an ID adds confusion as to how you would add new rules. Docs around the ID being OK to remove, or it not being in included if not required, will help avoid this confusion.

**Comment by willvedd** [comment]
@matt-filion Thanks for opening this issue and apologies for the long delay in response!

I can certainly understand the confusion around IDs being exported, especially since one of the main use cases is multi-tentant management. Fortunately, since the time you opened this ticket, rules and other resource type have omitted the exporting of ID. So this is no longer an issue. 

However, for other folks who have specific workflows that rely on IDs being exported, it's always possible to pass in the `--export_ids` flag to the export command.
