### ISSUE TITLE
Remove fields that don't seem to be a setting from custom-domains.json

### ISSUE THREAD

**Issue by shibayu36** [auth0/auth0-deploy-cli#600]
### Describe the problem you'd like to have solved

custom-domains.json seems to have fields that are not settings but states.  If this file has fields for a state, then it is difficult to manage a setting as a code.

custom-domains.json example is following
```json
[
  {
    "domain": "auth.example.com",
    "primary": true,
    "status": "ready",
    "type": "auth0_managed_certs",
    "verification": {
      "methods": [
        {
          "name": "cname",
          "record": "hoge-cd-fuga.edge.tenant-name.auth0.com"
        }
      ]
    },
    "tls_policy": "recommended"
  }
]
```

I think `domain`, `type`, `tls_policy` are settings, but `primary`, `status`, and `verification` are states or something else which auth0-deploy-cli should not manage.

### Describe the ideal solution
I think custom-domains.json should include only fields which is described by `POST /api/v2/custom-domains` ( https://auth0.com/docs/api/management/v2/#!/Custom_Domains/post_custom_domains ).  `domain`, `type`, `verification_method`, `tls_policy`, and `custom_client_ip_header`.

## Alternatives and current work-arounds

> A clear and concise description of any alternatives you've considered or any work-arounds that are currently in place.

### Additional context

> Add any other context or screenshots about the feature request here.

**Comment by willvedd** [comment]
You're correct that `status`,`primary` and `verification` are server-side-computed fields that are not configurable during creation. However, this is [accounted for in the handler ](https://github.com/auth0/auth0-deploy-cli/blob/bede9eec7d2401e2d9ea659a35d4a1b2108a6fd1/src/tools/auth0/handlers/customDomains.ts#L34) where those properties are removed upon creation. Custom domains are currently not able to be updated. You're welcome to omit those properties from your configuration files, but otherwise they serve as a read-only reference. 

Admittedly, the decision to include computed state properties instead of exclusively settings was not wise in hindsight. However, looking at the bigger picture, I personally don't see how the existence of these properties makes it difficult to manage the configuration as a whole, particularly due to the consideration that you can only create and delete custom domains and that you're able to delete those properties without consequence.
