### ISSUE TITLE
If would be nice if names were at the top, when exporting.

### ISSUE THREAD

**Issue by matt-filion** [auth0/auth0-deploy-cli#61]
When I create an export of an existing environment, in yaml, in some cases the 'name' attribute is a few attributes down. I am certain this is purely based on how the data is returned. However it would be a lot easier to navigate the resulting file if name, template, identifier and then id (in that order) were the first few elements (if they exist).

**Comment by giomaik** [comment]
Sorry to barge in, but that could be very useful as a feature idea. Also, the order of the different configuration objects is random, again I'm assuming because of the way they get returned by the API, which makes diffing on the yaml files to keep track of configuration changes very difficult. I'm not sure it is possible or even a priority for the team, just that it would be very useful if the produced yaml was predictably ordered. Thanks

**Comment by stevezau** [comment]
I was looking at support this as part of the v2 release but js-yaml didn't support ordering during dump. I agree this would be a nice to have.
