### ISSUE TITLE
Line break mode breaks multiline keys when importing for yaml

### ISSUE THREAD

**Issue by osrl** [auth0/auth0-deploy-cli#613]
### Description

I'm Github actions and had some single line environment keys which works perfectly.
I tried to add apple connection which needs a PEM format key, which is multiline.

a0deploy uses Folded style line breaks ( `>-` ) while importing the key. but it needs to use Linear style line breaks ( '|-' )

I tried to use this syntax too but it didn't work:
```
   app_secret: |-
        "##SECRET##"
```

### Environment
- a0deploy version: 7.14.1

**Comment by willvedd** [comment]
Appreciate you opening this ticket. You're certainly correct that the above example will fail. Unfortunately, the keyword replacement functionality is quite naive doesn't do much besides performing a literal swap, it is not contextually aware of its placement within a yaml doc.

However, I was able to tweak your example a bit to get it working. The key is to provide the appropriate amount of indentation to the replacement value itself. Otherwise, when the replacement happens, the YAML document will be invalid. Granted, adding indentation to the beginning of each line is not ideal, but it will work. 

```yaml
clients:
      - name: apple_connection
        app_secret: >-
          ##SECRET##
```

```json
{
    AUTH0_KEYWORD_REPLACE_MAPPINGS: {
        SECRET: `line1
            line2
            line3
          `,
      }
}
```
**Note:** `Both the line2` and `line3` strings are prepended with an appropriate amount of indentation.

This workaround is probably the best we can do for a little while. Implementing dedicated support, while certainly a good idea, would require a decent sized lift and we have other priorities. Though I'd be happy to support anyone who submits a PR with this functionality.
