### ISSUE TITLE
Actions Trigger Removal

### ISSUE THREAD

**Issue by ChrisSargent** [auth0/auth0-deploy-cli#623]
### Describe the problem you'd like to have solved

Currently, removing a trigger from the `triggers.json` file does not remove that trigger from the tenant

### Describe the ideal solution

In our dev environments we only allow login from specific email domains which is enforced by a pre-signup trigger. We no longer have the same requirement hence, we don't want to deploy that trigger.

Removing the trigger from the json should remove the trigger from the tenant, or at least passing an empty array.

```json
{
  "post-login": [
    {
      "pre-user-registration": "ForceEmailVerification",
      "display_name": "ForceEmailVerification"
    }
  ]
}
```
to 
```json
{
  "post-login": []
}
```

## Alternatives and current work-arounds

Trigger needs to be deleted from the UI and the IaC to ensure it is removed

### Additional context

For us, we are deploying or not deploying triggers dependent on environment, which we handle through replace mappings.

**Comment by willvedd** [comment]
When I test this myself, I'm able to confirm that explicitly setting a trigger's value to an empty array will unbind all actions from that trigger. Confirmed working both for YAML and directory formats. So from my point of view, I don't see an issue here.

>Removing the trigger from the json should remove the trigger from the tenant

Are you able to clarify here? Are you suggesting that setting an empty array value to a trigger should remove the _trigger_ from the tenant or the bound action? I think you mean the latter. And if so, that would be an overreach because actions can be bound to multiple triggers and you wouldn't just want to delete an action as soon as it isn't bound to a trigger.
