### ISSUE TITLE
Email template exported even though there are no changes

### ISSUE THREAD

**Issue by jcerjak** [auth0/auth0-deploy-cli#690]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/auth0-deploy-cli#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://github.com/auth0/auth0-deploy-cli#documentation) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-deploy-cli/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/auth0-deploy-cli/releases/latest) of this tool and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

If you ever edit an email template, then revert back to the original version, the exported data in `emailTemplates` will contain HTML for the edited template, even though there are no changes. 

Looks like this is because Auth0 has two template systems and there is no way to revert to the initial template: https://community.auth0.com/t/reset-default-email-template/59615

This is problematic because when looking at exported data, it looks like we have modified an email template. This is technically true, since the new default template is different than the initial template. However, we just want initial default state without any changes to the templates. This is to:
* Avoid confusion (why is this email template here, why was it modified?)
* Avoid potential problems if we will ever edit the template (someone might edit the template we have in our repo, and forget to check on Auth0 if there were any updates to the template)

### Expectation

I would expect to be able to go to default initial email templates, so that exported `emailTemplates` is empty. 

### Reproduction

Not sure what exact steps were. I don't want to try with another template, since then I'll have two templates exported in `emailTemplates`, while I just want the default empty state.

But it was something like:
* Enable custom email provider
* Edit Verification Email template
* Revert the changes by clicking `Reset`
* Disable the template
* Run export with `auth0-deploy-cli`
* Actual state: there is a file in exported data: `emailTemplates/verify_email.html`
* Desired state: there is no `emailTemplates/` directory (or directory is empty)

### Deploy CLI version

7.15.1

### Node version

v18.12.1

**Comment by jcerjak** [comment]
Similar problem for `pages`...

**Comment by willvedd** [comment]
Appreciate the feedback here. So to reiterate, this issue is to capture confusion around templates exporting their values despite being disabled or reverted to some default state? If so, I can certainly see where you're coming from. 

For better or worse, the [Auth0 Management API](https://auth0.com/docs/api/management/v2) persists certain configuration even if the state of that resource necessarily doesn't need that configuration to exist. And as you've discovered through the templates, the API keeps your old template values, even though you do not care about them anymore. While I can see how this may confuse some, I do see a practical use case for holding these configuration values.  And from the perspective of the Deploy CLI, destroying or omitting those template values based on the state of the resource is a bit of an overreach IMO. The modus operadi of this tool is too manage and migrate _all_ your Auth0 tenant configuration, despite it being a bit confusing at first. 

To address your initial issue, I may recommend blanking-out those email template values, deleting the directory won't do the job, you'll need to commit empty HTML templates. Hopefully that'll reduce some of the cognitive overhead.

**Comment by jcerjak** [comment]
Thanks for the explanation. Personally, I'd prefer if Auth0 Management API would not store and/or return the custom template, if it's exactly the same as the default template.

But we can live with the approach you suggested, feel free to close the ticket.
