### ISSUE TITLE
Issue when exporting tenant with --format directory

### ISSUE THREAD

**Issue by tavianm** [auth0/auth0-deploy-cli#722]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/auth0-deploy-cli#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://github.com/auth0/auth0-deploy-cli#documentation) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-deploy-cli/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/auth0-deploy-cli/releases/latest) of this tool and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Currently we're facing an issue with the grants files not created when exporting our tenant with format directory. It's working in 7.15.1

### Expectation

Before version 7.15.2, when exporting the tenant like that, the grants were created as one file per couple application / (audience) named as "applicationName (audience)" example:  Grants APi (urn-api-test) .
Each file having the scopes intended.

### Reproduction

Given a M2M application which has authorizations with multiples audience, when exporting the tenant has directory, then a unique grant's file is created by application named "applicationName" containing the scope of only one audience.  

### Deploy CLI version

7.15.2

### Node version

18.12.1 / 14.20.1

**Comment by willvedd** [comment]
@tavianm Thanks for opening this issue.

My understanding of your issue is that previously in 7.15.1, you had separate client grants created for each client-audience pair. Whereas now in 7.15.2, the client grants are only created for each client. The critical issue here is that each client grant file only contains a grant for a single audience, instead of encoding data for _all_ audiences. Do I understand correctly?

This is a change that was introduced in #684 to address #459. The main issue being that the audience was unique to a tenant which violates the tenant-agnostic nature of this tool. However, I can certainly see how the issue you described could occur.

I still believe that it's best to keep the configuration files detached from a specific tenant. Given your use case, do you think that it would be suitable to put all of a specific client's grants into a single file or do you think each client-audience requires its own file?

**Comment by tavianm** [comment]
Hi @willvedd !

You understood perfectly!

I didn't notice the previous pull request about client grants files and I agree that audience, which is tenant dependent, was kind of tricky to use in some cases.

The fact is that without this "audience dependent" file's naming, I don't see how to name grants files :( 
( maybe client1.json, client2.json, client3.json ... or something else generic) 

Otherwise, to works with one grant's file by client, it will need a rework in the logic of both export / import to work.  This seems more tricky to develop

**Comment by willvedd** [comment]
@tavianm Thanks for remaining patience on this! We've introduced a fix for this in [7.16.1](https://github.com/auth0/auth0-deploy-cli/releases/tag/v7.16.1). So now all client grants should be exported with the directory format. Additionally, we've improved the naming of these files to be tenant-agnostic. Going to mark this as closed, but please feel free to provide feedback on the change!
